export * from "./isGlobalOnly";
export * from "./isGoal";
export * from "./isIndicator";
export * from "./isLnobAssessment";
export * from "./isOecdOnly";
export * from "./isOverallAssessment";
export * from "./isRelevantIndicatorForRegion";
export * from "./isSpilloverAssessment";
export * from "./isTrendIndicator";
